version: '3.8'
services:
  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: graylog
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  
  elasticsearch:
    image: elasticsearch:7.9.3
    ports:
      - 9200:9200
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"

  graylog2:
    build: 
      context: ./graylog
      args:
        GRAYLOG_VERSION: 4.0.1
    image: graylog
    container_name: graylog
    ports:
     - "9000:9000"
     - "12201:12201"
     - "1514:1514"
     - "5555:5555"
    links:
     - elasticsearch
     - mongo
    depends_on: 
     - mongo
     - elasticsearch
